// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs


Table fact_rental_paymen {
  rental_payment_id integer [primary key]
  custormer_adress_id integer
  inventory_id integer
  staff_id integer
  rental_days integer
  payment_overdue_days integer
  rental_date_id integer
  retirn_date_id integer
  payment_deadline_id integer
  SK_store_id integer
  payment_amount decimal
  rental_amount decimal
  rental_rate decimal
}

Table dim_customer {
  custormer_id integer [primary key]
  customer_key integer
  customer_name varchar
  customer_email varchar
  customer_birth_date DATE
  customer_address varchar      // kolumny dołączona z tabeli address
  customer_postal_code varchar  //
  customer_city varchar         //
  customer_country varchar      //
}

Table dim_inventory {
  inventory_id integer [primary key]
  inventory_key intiger
  inventory_fuel_type varchar
  inventory_production_year date
  inventory_producer varchar     // kolumny dołączone z tabeli car
  inventory_model varchar        //
  inventory_address varchar      // kolumna dołączona, wynika z założeń zadania
  inventory_postal_code varchar  // ???
  inventory_city varchar         // ???
  inventory_country varchar      // ???
}

Table bridge_inventory_equipment {
  inventory_id integer [primary key]
  equipment_id integer [primary key]
}

Table dim_equipment {
  equipment_id integer [primary key]
  equipment_key intiger
  equipment_name varchar
  equipment_type varchar
  equipment_version varchar
}

Table dim_staff {
  staff_id integer [primary key]
  staff_key intiger
  staff_name varchar
  staff_manager_name varchar
  staff_address varchar      // kolumna dołączona, wynika z założeń zadania
  staff_postal_code varchar  // ???
  staff_city varchar         // ???
  staff_country varchar      // ???
}

Table dim_store {
  store_id integer [primary key] // scd2
  store_key intiger
  store_address varchar        // kolumna dołączona, wynika z założeń zadania 
  store_postal_code varchar    //
  store_city varchar           //
  store_country varchar        //
  store_manager_id integer
  store_manager_name varchar
  store_is_active bool
  store_valid_from date
  store_valid_to date
}

Table dim_calendar {
  calendar_id integer [primary key]
  calendar_full_date_str varchar
  calendar_full_date date
  calendar_year integer
  calendar_quarter integer
  calendar_month integer
  calendar_day integer
  calendar_weekday integer
  calendar_weekday_str varchar
  calendar_is_month_end bool
}

Table fact_service {
  service_id integer [primary key]
  inventory_id integer
  service_date_id integer
  service_type varchar
  service_cost decimal
}

Ref: dim_customer.custormer_id < fact_rental_paymen.custormer_adress_id
Ref: dim_inventory.inventory_id < fact_rental_paymen.inventory_id
Ref: dim_staff.staff_id < fact_rental_paymen.staff_id
Ref: dim_store.store_id < fact_rental_paymen.SK_store_id
Ref: dim_calendar.calendar_id < fact_rental_paymen.rental_date_id
Ref: dim_calendar.calendar_id < fact_rental_paymen.retirn_date_id
Ref: dim_calendar.calendar_id < fact_rental_paymen.payment_deadline_id
Ref: dim_inventory.inventory_id < bridge_inventory_equipment.inventory_id
Ref: dim_equipment.equipment_id < bridge_inventory_equipment.equipment_id
Ref: dim_inventory.inventory_id < fact_service.inventory_id
Ref: dim_calendar.calendar_id < fact_service.service_date_id

